create table if not exists public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  name text not null,
  role text not null default 'siswa' check (role in ('admin', 'guru', 'siswa')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.data_siswa (
  id bigint generated by default as identity primary key,
  nama text not null check (char_length(nama) between 1 and 255),
  nisn text not null unique check (char_length(nisn) between 1 and 255),
  photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.data_guru (
  id bigint generated by default as identity primary key,
  nama text not null check (char_length(nama) between 1 and 255),
  nip text not null unique check (char_length(nip) between 1 and 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.data_kelas (
  id bigint generated by default as identity primary key,
  nama_kelas text not null check (char_length(nama_kelas) between 1 and 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tahun_ajaran (
  id bigint generated by default as identity primary key,
  tahun_ajaran text not null check (char_length(tahun_ajaran) between 1 and 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.data_pelajaran (
  id bigint generated by default as identity primary key,
  nama_pelajaran text not null check (char_length(nama_pelajaran) between 1 and 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.semester (
  id bigint generated by default as identity primary key,
  semester text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wali_kelas (
  id bigint generated by default as identity primary key,
  guru_id bigint not null references public.data_guru (id) on delete cascade,
  kelas_id bigint not null references public.data_kelas (id) on delete cascade,
  tahun_ajaran_id bigint not null references public.tahun_ajaran (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (guru_id, kelas_id, tahun_ajaran_id)
);

create table if not exists public.siswa_kelas (
  id bigint generated by default as identity primary key,
  kelas_id bigint not null references public.data_kelas (id) on delete cascade,
  siswa_id bigint not null references public.data_siswa (id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, name)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute procedure public.set_updated_at();
drop trigger if exists data_siswa_set_updated_at on public.data_siswa;
create trigger data_siswa_set_updated_at before update on public.data_siswa
  for each row execute procedure public.set_updated_at();
drop trigger if exists data_guru_set_updated_at on public.data_guru;
create trigger data_guru_set_updated_at before update on public.data_guru
  for each row execute procedure public.set_updated_at();
drop trigger if exists data_kelas_set_updated_at on public.data_kelas;
create trigger data_kelas_set_updated_at before update on public.data_kelas
  for each row execute procedure public.set_updated_at();
drop trigger if exists tahun_ajaran_set_updated_at on public.tahun_ajaran;
create trigger tahun_ajaran_set_updated_at before update on public.tahun_ajaran
  for each row execute procedure public.set_updated_at();
drop trigger if exists data_pelajaran_set_updated_at on public.data_pelajaran;
create trigger data_pelajaran_set_updated_at before update on public.data_pelajaran
  for each row execute procedure public.set_updated_at();
drop trigger if exists semester_set_updated_at on public.semester;
create trigger semester_set_updated_at before update on public.semester
  for each row execute procedure public.set_updated_at();
drop trigger if exists wali_kelas_set_updated_at on public.wali_kelas;
create trigger wali_kelas_set_updated_at before update on public.wali_kelas
  for each row execute procedure public.set_updated_at();
drop trigger if exists siswa_kelas_set_updated_at on public.siswa_kelas;
create trigger siswa_kelas_set_updated_at before update on public.siswa_kelas
  for each row execute procedure public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where user_id = (select auth.uid()) and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.data_siswa to authenticated;
grant select, insert, update, delete on public.data_guru to authenticated;
grant select, insert, update, delete on public.data_kelas to authenticated;
grant select, insert, update, delete on public.tahun_ajaran to authenticated;
grant select, insert, update, delete on public.data_pelajaran to authenticated;
grant select, insert, update, delete on public.semester to authenticated;
grant select, insert, update, delete on public.wali_kelas to authenticated;
grant select, insert, update, delete on public.siswa_kelas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles enable row level security;
alter table public.data_siswa enable row level security;
alter table public.data_guru enable row level security;
alter table public.data_kelas enable row level security;
alter table public.tahun_ajaran enable row level security;
alter table public.data_pelajaran enable row level security;
alter table public.semester enable row level security;
alter table public.wali_kelas enable row level security;
alter table public.siswa_kelas enable row level security;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles
  for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
drop policy if exists profiles_admin_manage on public.profiles;
create policy profiles_admin_manage on public.profiles
  for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

drop policy if exists data_siswa_admin_all on public.data_siswa;
create policy data_siswa_admin_all on public.data_siswa for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists data_guru_admin_all on public.data_guru;
create policy data_guru_admin_all on public.data_guru for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists data_kelas_admin_all on public.data_kelas;
create policy data_kelas_admin_all on public.data_kelas for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists tahun_ajaran_admin_all on public.tahun_ajaran;
create policy tahun_ajaran_admin_all on public.tahun_ajaran for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists data_pelajaran_admin_all on public.data_pelajaran;
create policy data_pelajaran_admin_all on public.data_pelajaran for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists semester_admin_all on public.semester;
create policy semester_admin_all on public.semester for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists wali_kelas_admin_all on public.wali_kelas;
create policy wali_kelas_admin_all on public.wali_kelas for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists siswa_kelas_admin_all on public.siswa_kelas;
create policy siswa_kelas_admin_all on public.siswa_kelas for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('student-photos', 'student-photos', false, 2097152, array['image/jpeg', 'image/png', 'image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists student_photos_admin_read on storage.objects;
create policy student_photos_admin_read on storage.objects for select to authenticated
  using (bucket_id = 'student-photos' and (select public.is_admin()));
drop policy if exists student_photos_admin_insert on storage.objects;
create policy student_photos_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'student-photos' and (select public.is_admin()));
drop policy if exists student_photos_admin_update on storage.objects;
create policy student_photos_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'student-photos' and (select public.is_admin()))
  with check (bucket_id = 'student-photos' and (select public.is_admin()));
drop policy if exists student_photos_admin_delete on storage.objects;
create policy student_photos_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'student-photos' and (select public.is_admin()));