-- Schema ujian terpisah dari supabase-schema.sql.
-- Jalankan supabase-schema.sql terlebih dahulu karena skrip ini memakai
-- data_siswa, data_pelajaran, profiles, dan public.is_admin().

DO $$
BEGIN
  CREATE TYPE public.soal_type AS ENUM ('pg', 'essay');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS public.ujian (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_ujian text NOT NULL CHECK (char_length(trim(nama_ujian)) BETWEEN 1 AND 255),
  pelajaran_id bigint NOT NULL REFERENCES public.data_pelajaran (id) ON DELETE RESTRICT,
  waktu_menit integer NOT NULL CHECK (waktu_menit > 0),
  dibuka_at timestamptz NOT NULL,
  ditutup_at timestamptz NOT NULL,
  acak_soal boolean NOT NULL DEFAULT false,
  acak_jawaban boolean NOT NULL DEFAULT false,
  aktif boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (dibuka_at < ditutup_at)
);

CREATE TABLE IF NOT EXISTS public.soal_ujian (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ujian_id bigint NOT NULL REFERENCES public.ujian (id) ON DELETE CASCADE,
  nomor_urut integer NOT NULL CHECK (nomor_urut > 0),
  soal_type public.soal_type NOT NULL,
  pertanyaan text NOT NULL CHECK (char_length(trim(pertanyaan)) > 0),
  pilihan_a text,
  pilihan_b text,
  pilihan_c text,
  pilihan_d text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ujian_id, nomor_urut),
  UNIQUE (id, ujian_id),
  CHECK (
    (soal_type = 'pg' AND pilihan_a IS NOT NULL AND pilihan_b IS NOT NULL
      AND pilihan_c IS NOT NULL AND pilihan_d IS NOT NULL)
    OR
    (soal_type = 'essay' AND pilihan_a IS NULL AND pilihan_b IS NULL
      AND pilihan_c IS NULL AND pilihan_d IS NULL)
  )
);

ALTER TABLE public.soal_ujian DROP COLUMN IF EXISTS nilai_maksimum;

-- Kunci pilihan ganda dipisah agar tidak ikut terbaca bersama teks soal.
CREATE TABLE IF NOT EXISTS public.kunci_pg (
  soal_id bigint PRIMARY KEY REFERENCES public.soal_ujian (id) ON DELETE CASCADE,
  jawaban_benar char(1) NOT NULL CHECK (jawaban_benar IN ('A', 'B', 'C', 'D'))
);

-- Satu soal essay dapat menerima beberapa jawaban acuan/variasi.
CREATE TABLE IF NOT EXISTS public.jawaban_acuan_essay (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  soal_id bigint NOT NULL REFERENCES public.soal_ujian (id) ON DELETE CASCADE,
  jawaban text NOT NULL CHECK (char_length(trim(jawaban)) > 0),
  UNIQUE (soal_id, jawaban)
);

CREATE TABLE IF NOT EXISTS public.percobaan_ujian (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ujian_id bigint NOT NULL REFERENCES public.ujian (id) ON DELETE RESTRICT,
  siswa_id bigint NOT NULL REFERENCES public.data_siswa (id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'berlangsung'
    CHECK (status IN ('berlangsung', 'dikumpulkan', 'dinilai')),
  mulai_at timestamptz NOT NULL DEFAULT now(),
  dikumpulkan_at timestamptz,
  nilai_pilihan_ganda numeric(8, 2) CHECK (nilai_pilihan_ganda >= 0),
  nilai_essay_final numeric(8, 2) CHECK (nilai_essay_final >= 0),
  nilai_total numeric(8, 2) CHECK (nilai_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, ujian_id)
);

CREATE TABLE IF NOT EXISTS public.jawaban_siswa (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  percobaan_id bigint NOT NULL,
  ujian_id bigint NOT NULL,
  soal_id bigint NOT NULL,
  urutan_soal integer NOT NULL CHECK (urutan_soal > 0),
  urutan_opsi_tampil text[],
  jawaban_pg char(1) CHECK (jawaban_pg IN ('A', 'B', 'C', 'D')),
  jawaban_essay text,
  nilai_otomatis numeric(8, 2) CHECK (nilai_otomatis >= 0),
  status_ai text CHECK (status_ai IN ('menunggu', 'cocok', 'perlu_tinjau', 'tidak_cocok', 'gagal')),
  nilai_ai numeric(8, 2) CHECK (nilai_ai >= 0),
  catatan_ai text,
  nilai_final numeric(8, 2) CHECK (nilai_final >= 0),
  catatan_guru text,
  ditinjau_oleh uuid REFERENCES public.profiles (user_id) ON DELETE SET NULL,
  ditinjau_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (percobaan_id, ujian_id)
    REFERENCES public.percobaan_ujian (id, ujian_id) ON DELETE CASCADE,
  FOREIGN KEY (soal_id, ujian_id)
    REFERENCES public.soal_ujian (id, ujian_id) ON DELETE CASCADE,
  UNIQUE (percobaan_id, soal_id),
  UNIQUE (percobaan_id, urutan_soal),
  CHECK (jawaban_pg IS NULL OR jawaban_essay IS NULL),
  CHECK (urutan_opsi_tampil IS NULL OR cardinality(urutan_opsi_tampil) = 4)
);

CREATE INDEX IF NOT EXISTS ujian_pelajaran_aktif_idx
  ON public.ujian (pelajaran_id, aktif);
CREATE INDEX IF NOT EXISTS ujian_jadwal_aktif_idx
  ON public.ujian (dibuka_at, ditutup_at) WHERE aktif;
CREATE INDEX IF NOT EXISTS soal_ujian_ujian_urut_idx
  ON public.soal_ujian (ujian_id, nomor_urut);
CREATE INDEX IF NOT EXISTS percobaan_ujian_siswa_idx
  ON public.percobaan_ujian (siswa_id, ujian_id);
CREATE INDEX IF NOT EXISTS jawaban_siswa_ujian_idx
  ON public.jawaban_siswa (percobaan_id, ujian_id);

DROP TRIGGER IF EXISTS ujian_set_updated_at ON public.ujian;
CREATE TRIGGER ujian_set_updated_at BEFORE UPDATE ON public.ujian
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS soal_ujian_set_updated_at ON public.soal_ujian;
CREATE TRIGGER soal_ujian_set_updated_at BEFORE UPDATE ON public.soal_ujian
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS percobaan_ujian_set_updated_at ON public.percobaan_ujian;
CREATE TRIGGER percobaan_ujian_set_updated_at BEFORE UPDATE ON public.percobaan_ujian
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();
DROP TRIGGER IF EXISTS jawaban_siswa_set_updated_at ON public.jawaban_siswa;
CREATE TRIGGER jawaban_siswa_set_updated_at BEFORE UPDATE ON public.jawaban_siswa
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ujian TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.soal_ujian TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.kunci_pg TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.jawaban_acuan_essay TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.percobaan_ujian TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.jawaban_siswa TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE
  public.ujian_id_seq,
  public.soal_ujian_id_seq,
  public.jawaban_acuan_essay_id_seq,
  public.percobaan_ujian_id_seq,
  public.jawaban_siswa_id_seq
TO authenticated;

ALTER TABLE public.ujian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.soal_ujian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kunci_pg ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jawaban_acuan_essay ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.percobaan_ujian ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jawaban_siswa ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ujian_admin_all ON public.ujian;
CREATE POLICY ujian_admin_all ON public.ujian FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS soal_ujian_admin_all ON public.soal_ujian;
CREATE POLICY soal_ujian_admin_all ON public.soal_ujian FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS kunci_pg_admin_all ON public.kunci_pg;
CREATE POLICY kunci_pg_admin_all ON public.kunci_pg FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS jawaban_acuan_essay_admin_all ON public.jawaban_acuan_essay;
CREATE POLICY jawaban_acuan_essay_admin_all ON public.jawaban_acuan_essay FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS percobaan_ujian_admin_all ON public.percobaan_ujian;
CREATE POLICY percobaan_ujian_admin_all ON public.percobaan_ujian FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
DROP POLICY IF EXISTS jawaban_siswa_admin_all ON public.jawaban_siswa;
CREATE POLICY jawaban_siswa_admin_all ON public.jawaban_siswa FOR ALL TO authenticated
  USING ((SELECT public.is_admin())) WITH CHECK ((SELECT public.is_admin()));
